services:
  mysql:
    image: mariadb:10.6
    container_name: ssnyd-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ssnyd_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: ssnyd-bot
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ssnyd_bot_data:/data

volumes:
  ssnyd_mysql_data:
  ssnyd_bot_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
